{
 "title": "Matomo",
 "tags": [
  "matomo",
  "websites"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "site",
    "query": {
     "query": "label_values(number_of_visited_pages_current_yearly,site_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Visits previous day",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "number_of_visits{site_name=\"$site\", period=\"previous_day\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Visits today",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "number_of_visits{site_name=\"$site\", period=\"day\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Uniques visitors per day",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "number_uniq_visitors{job=\"matomo\", site_name=\"$site\", period=\"previous_day\"}",
     "legendFormat": "{{site_name}}"
    }
   ]
  },
  {
   "title": "Uniques visitors per day",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "number_of_visits{job=\"matomo\", site_name=\"$site\", period=\"day\"}",
     "legendFormat": "{{site_name}}"
    }
   ]
  },
  {
   "title": "Percentage of new visitors",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "number_uniq_visitors{site_name=\"une-tasse-de.cafe\", period=\"day\"} / number_of_visits{site_name=\"une-tasse-de.cafe\", period=\"day\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Most visited pages today",
   "type": "table",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "number_of_visit_per_page{site_name=\"$site\", period=\"day\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Most visited pages in the month",
   "type": "table",
   "gridPos": { "h": 11, "w": 4, "x": 4, "y": 6 },
   "targets": [
    {
     "expr": "number_of_visit_per_page{site_name=\"$site\", period=\"month\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Most visited pages in the year",
   "type": "table",
   "gridPos": { "h": 11, "w": 4, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "number_of_visit_per_page{site_name=\"$site\", period=\"year\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OS Versions",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "number_of_visitors_per_os_version{site_name=\"une-tasse-de.cafe\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}